---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: day2-bme-lab
  namespace: openshift-gitops
spec:
  generators:
    - matrix:
        generators:
          - list:
              elements:
                - appName: ingresscontroller-default
                  path: live/ingresscontroller-default
                  revision: main
                - appName: oauth
                  path: live/oauth
                  revision: main
                - appName: self-provisioning
                  path: live/self-provisioning
                  revision: main
          - clusters:
              selector:
                matchLabels:
  strategy:
    type: RollingSync
    rollingSync:
      steps:
        - matchExpressions:
            - key: compLabel
              operator: In
              values:
                - oauth
        - matchExpressions:
            - key: compLabel
              operator: In
              values:
                - ingresscontroller-default
        - matchExpressions:
            - key: compLabel
              operator: In
              values:
                - self-provisioning
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  syncPolicy:
    preserveResourceOnDeletion: true
  template:
    metadata:
      name: "{{.appName}}-bme-lab"
      labels:
        compLabel: "{{.appName}}"
    spec:
      destination:
        namespace: default
        server: "{{.server}}"
      project: bme-lab
      sources:
        - path: "{{.path}}"
          repoURL: "https://github.com/ObieBent/bme-lab.git"
          targetRevision: "{{.revision}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - PruneLast=true
