apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - github.com/ObieBent/ocp-gitops-catalog/bases/ingresscontroller-default?ref=main
patches:
  - path: patch_console.yaml
    target:
      group: config.openshift.io
      version: v1
      kind: Ingress
      name: cluster
